/**
 * Field metadata dictionary for all SINTER property fields
 * Contains descriptions, formats, obligatoriness, validation rules, and examples.
 */

export interface FieldHelpInfo {
  key: string;
  label: string;
  description: string;
  format: string;
  mandatoryRule: string;
  rules: string;
  example: string;
  cleanFilter?: (val: string) => string;
}

export const SINTER_FIELDS_HELP: Record<string, FieldHelpInfo> = {
  inscricaoImobiliaria: {
    key: 'inscricaoImobiliaria',
    label: 'Inscrição Imobiliária',
    description: 'Código oficial de identificação do imóvel na base cadastral municipal.',
    format: 'String (até 45 caracteres)',
    mandatoryRule: 'Obrigatório para todos os tipos (Tipo 1, 2 e 3).',
    rules: 'Não pode conter caracteres de controle invisíveis. Máximo de 45 caracteres.',
    example: '1234567890123456789012345',
  },
  tipoImovel: {
    key: 'tipoImovel',
    label: 'Tipo do Imóvel',
    description: 'Classificação oficial da natureza do imóvel segundo a tabela de domínio do SINTER.',
    format: 'Inteiro (1, 2 ou 3)',
    mandatoryRule: 'Obrigatório.',
    rules: '1 = Territorial (lote/terreno), 2 = Predial (com edificação), 3 = Bem imóvel de características especiais (BICE).',
    example: '2',
  },
  tpArquitetonico: {
    key: 'tpArquitetonico',
    label: 'Tipo Arquitetônico',
    description: 'Tipo arquitetônico da edificação (ex.: casa, apartamento, sala, galpão, prédio).',
    format: 'Inteiro (Código de domínio SINTER)',
    mandatoryRule: 'Se tipoImovel = 1 → Não deve ser informado. Se tipoImovel = 2 → Obrigatório. Se tipoImovel = 3 → Opcional.',
    rules: 'Quando tipoImovel = 1 e tpArquitetonico preenchido, o imóvel não recebe CIB.',
    example: '1 (Casa) ou 2 (Apartamento)',
  },
  destinacaoImovel: {
    key: 'destinacaoImovel',
    label: 'Destinação do Imóvel',
    description: 'Finalidade de uso do imóvel (ex.: residencial, comercial, industrial, serviço).',
    format: 'Inteiro (Código de domínio SINTER)',
    mandatoryRule: 'Se tipoImovel = 1 → Opcional. Se tipoImovel = 2 → Obrigatório. Se tipoImovel = 3 → Opcional.',
    rules: 'Valores conforme tabela de domínio (1 = Residencial, 2 = Comercial, etc.).',
    example: '1 (Residencial)',
  },
  areaTerreno: {
    key: 'areaTerreno',
    label: 'Área do Terreno (m²)',
    description: 'Área total da superfície do terreno em metros quadrados.',
    format: 'Numérico (até 12 inteiros + até 4 decimais)',
    mandatoryRule: 'Obrigatório (> 0 m²).',
    rules: 'Deve ser maior que 0. Máximo 12 dígitos na parte inteira e 4 casas decimais.',
    example: '350.7500',
  },
  areaConstruida: {
    key: 'areaConstruida',
    label: 'Área Construída (m²)',
    description: 'Área total construída/edificada no imóvel em metros quadrados.',
    format: 'Numérico (até 12 inteiros + até 4 decimais)',
    mandatoryRule: 'Se tipoImovel = 1 → Não deve ser informado. Se tipoImovel = 2 → Obrigatório (> 0). Se tipoImovel = 3 → Opcional.',
    rules: 'Quando tipoImovel = 1 e areaConstruida preenchida, não recebe CIB no SINTER.',
    example: '120.5000',
  },
  idParcela: {
    key: 'idParcela',
    label: 'Identificador da Parcela / Lote',
    description: 'Código identificador da parcela territorial ou lote correspondente.',
    format: 'String (até 35 caracteres)',
    mandatoryRule: 'Opcional. Se tipoImovel = 1 e informado → Gera FALHA no SINTER. Para Tipo 2 e 3 é opcional.',
    rules: 'Não deve ser informado para imóveis territoriais (Tipo 1). Máximo 35 caracteres.',
    example: 'PARC-12345',
  },
  anoConstrutivo: {
    key: 'anoConstrutivo',
    label: 'Ano Construtivo',
    description: 'Ano em que a edificação foi concluída ou averbada.',
    format: 'Inteiro (4 dígitos: AAAA)',
    mandatoryRule: 'Se tipoImovel = 1 e informado → Gera mensagem de Falha. Se tipoImovel = 2 → Obrigatório.',
    rules: 'Deve ser um ano de 4 dígitos válido (ex.: 2005). Para Tipo 1 não deve ser enviado.',
    example: '2005',
  },
  valorVenal: {
    key: 'valorVenal',
    label: 'Valor Venal (R$)',
    description: 'Valor venal cadastral atribuído pela prefeitura municipal para fins tributários (IPTU).',
    format: 'Numérico (até 18 inteiros + 2 decimais)',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: 'Número positivo. Máximo 18 dígitos inteiros e 2 casas decimais.',
    example: '450000.00',
  },
  dtUltimoValorVenal: {
    key: 'dtUltimoValorVenal',
    label: 'Data do Último Valor Venal',
    description: 'Data de fixação ou atualização da última avaliação de valor venal.',
    format: 'Data no padrão ISO: YYYY-MM-DD',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: 'Ano com 4 dígitos, mês e dia com 2 dígitos separados por hífen.',
    example: '2024-12-01',
  },
  padraoConstrutivo: {
    key: 'padraoConstrutivo',
    label: 'Padrão Construtivo',
    description: 'Classificação do padrão de acabamento da construção.',
    format: 'Inteiro (1 a 5)',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: '1 = Popular, 2 = Baixo, 3 = Normal, 4 = Alto, 5 = Luxo.',
    example: '3 (Normal)',
  },
  qtdGaragem: {
    key: 'qtdGaragem',
    label: 'Quantidade de Garagens',
    description: 'Número de vagas de garagem cobertas ou privativas do imóvel.',
    format: 'Inteiro (até 3 dígitos: 0 a 999)',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: 'Valor numérico inteiro entre 0 e 999.',
    example: '2',
  },
  temPiscina: {
    key: 'temPiscina',
    label: 'Tem Piscina?',
    description: 'Indica se a unidade imobiliária possui piscina instalada.',
    format: 'Booleano (true ou false)',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: 'true = Sim, possui piscina; false = Não possui.',
    example: 'false',
  },
  valorRefMercado: {
    key: 'valorRefMercado',
    label: 'Valor de Referência de Mercado (R$)',
    description: 'Valor de mercado estimado ou apurado em Planta de Valores Genéricos (PVG) ou avaliação municipal.',
    format: 'Numérico (até 18 inteiros + 2 decimais)',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: 'Número positivo. Máximo 18 dígitos inteiros e 2 casas decimais.',
    example: '520000.00',
  },
  dataUltValorMercado: {
    key: 'dataUltValorMercado',
    label: 'Data da Última Atualização de Mercado',
    description: 'Data da apuração ou fixação do valor de referência de mercado.',
    format: 'Data no padrão ISO: YYYY-MM-DD',
    mandatoryRule: 'Opcional (Modo Avançado).',
    rules: 'Ano com 4 dígitos, mês e dia com 2 dígitos separados por hífen.',
    example: '2024-12-15',
  },
  areaPrivativa: {
    key: 'areaPrivativa',
    label: 'Área Privativa (m²)',
    description: 'Área de uso exclusivo da unidade imobiliária (apartamento, sala, casa em condomínio).',
    format: 'Numérico - 12 inteiros + 4 decimais',
    mandatoryRule: 'Opcional para tipoImovel=2 ou 3. Não preenchida para tipoImovel=1.',
    rules: 'Não deve ser preenchida para imóveis territoriais (Tipo 1). Limite de 12 inteiros e 4 casas decimais.',
    example: '78.5000',
  },
  areaComum: {
    key: 'areaComum',
    label: 'Área Comum (m²)',
    description: 'Área de uso comum proporcional vinculada à unidade imobiliária em condomínio.',
    format: 'Numérico - 12 inteiros + 4 decimais',
    mandatoryRule: 'Opcional para tipoImovel=2 ou 3. Não preenchida para tipoImovel=1.',
    rules: 'Não deve ser preenchida para imóveis territoriais (Tipo 1). Limite de 12 inteiros e 4 casas decimais.',
    example: '24.3500',
  },
  fraIdeal: {
    key: 'fraIdeal',
    label: 'Fração Ideal do Terreno',
    description: 'Fração ideal indivisível da área total do terreno correspondente à unidade imobiliária autônoma.',
    format: 'Numérico - 1 inteiro + 4 decimais',
    mandatoryRule: 'Opcional para tipoImovel=2 ou 3. Não preenchida para tipoImovel=1.',
    rules: 'Não deve ser preenchida para imóveis territoriais (Tipo 1). Limite de 1 inteiro e 4 casas decimais (ex: 0.0450 a 1.0000).',
    example: '0.0425',
  },
  bice: {
    key: 'bice',
    label: 'Código BICE (Bens de Características Especiais)',
    description: 'Classificação de bens imóveis de características especiais (ex.: usinas, portos, praças, ferrovias, terras indígenas).',
    format: 'Inteiro (código 01 a 12)',
    mandatoryRule: 'Obrigatório se tipoImovel = 3. Não aplicável para Tipo 1 e Tipo 2.',
    rules: 'Campo obrigatório para Tipo 3. Deve ser um código válido da tabela oficial BICE (01 a 12).',
    example: '1 (Usinas)',
  },
  temBairro: {
    key: 'temBairro',
    label: 'Tem Bairro?',
    description: 'Indica se o município possui divisão territorial/política formal em bairros na localidade do imóvel.',
    format: 'Booleano (true ou false)',
    mandatoryRule: 'Obrigatório para todos os tipos.',
    rules: 'Se marcado como true, o preenchimento do campo Bairro torna-se obrigatório.',
    example: 'true',
  },
  tipoLogradouro: {
    key: 'tipoLogradouro',
    label: 'Tipo de Logradouro',
    description: 'Classificação do logradouro conforme a tabela DNER/IBGE/SINTER (ex.: Rua, Avenida, Travessa, Rodovia, Alameda).',
    format: 'Inteiro (Código oficial SINTER)',
    mandatoryRule: 'Obrigatório para todos os tipos.',
    rules: 'Código numérico correspondente ao tipo de via (ex: 250 = Rua, 28 = Avenida).',
    example: '250 (Rua)',
  },
  nomeLogradouro: {
    key: 'nomeLogradouro',
    label: 'Nome do Logradouro',
    description: 'Nome oficial da via pública onde o imóvel está situado.',
    format: 'String (até 300 caracteres)',
    mandatoryRule: 'Obrigatório para todos os tipos.',
    rules: 'Sem caracteres de controle. Máximo de 300 caracteres.',
    example: 'AVENIDA PAULISTA',
  },
  numeroImovel: {
    key: 'numeroImovel',
    label: 'Número do Imóvel',
    description: 'Numeração predial ou cadastral do imóvel no logradouro.',
    format: 'String (até 8 caracteres)',
    mandatoryRule: 'Opcional (Preencher com S/N ou deixar vazio se sem número).',
    rules: 'Máximo de 8 caracteres conforme especificação SINTER.',
    example: '1500',
  },
  complNroImovel: {
    key: 'complNroImovel',
    label: 'Complemento do Número',
    description: 'Identificação específica da unidade (ex.: APTO 101, BLOCO B, SALA 402, CASA 2).',
    format: 'String (até 30 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Máximo de 30 caracteres para individualizar apartamentos, salas e blocos.',
    example: 'APTO 302',
  },
  complEndereco: {
    key: 'complEndereco',
    label: 'Complemento do Endereço',
    description: 'Informações adicionais do local (ex.: EDIFÍCIO DAS FLORES, CONDOMÍNIO SOLAR, KM 12).',
    format: 'String (até 30 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Máximo de 30 caracteres conforme especificação SINTER.',
    example: 'EDIF SOLAR ACACIAS',
  },
  bairro: {
    key: 'bairro',
    label: 'Bairro',
    description: 'Nome do bairro ou distrito onde o imóvel está localizado.',
    format: 'String (até 30 caracteres)',
    mandatoryRule: 'Obrigatório para Tipo 2 e Tipo 3, e quando "Tem Bairro" for verdadeiro.',
    rules: 'Máximo de 30 caracteres conforme limite do SINTER.',
    example: 'CENTRO',
  },
  cep: {
    key: 'cep',
    label: 'CEP',
    description: 'Código de Endereçamento Postal brasileiro da localidade/logradouro.',
    format: 'String (exatamente 8 dígitos numéricos)',
    mandatoryRule: 'Obrigatório para todos os tipos.',
    rules: 'Deve conter exatamente 8 dígitos numéricos, sem hífens ou pontos.',
    example: '70000000',
  },
  operacao: {
    key: 'operacao',
    label: 'Operação Cadastral (operacao)',
    description: 'Tipo de ação a ser executada pelo SINTER para este registro imobiliário.',
    format: 'String (I, A, E)',
    mandatoryRule: 'Opcional (Padrão: I = Inclusão).',
    rules: 'I = Inclusão de novo imóvel, A = Alteração/Atualização de dados cadastrais, E = Exclusão/Desativação de imóvel.',
    example: 'I (Inclusão)',
  },
  niTitular: {
    key: 'niTitular',
    label: 'NI do Titular (CPF / CNPJ)',
    description: 'Número de identificação fiscal (CPF de 11 dígitos ou CNPJ de 14 dígitos) do proprietário ou possuidor.',
    format: 'Numérico (11 dígitos para CPF, 14 para CNPJ)',
    mandatoryRule: 'Opcional. Deve ser numérico.',
    rules: 'Sem caracteres especiais (pontos ou traços). Exatamente 11 dígitos para Pessoa Física ou 14 dígitos para Pessoa Jurídica.',
    example: '12345678901 ou 12345678000199',
  },
  nomeTitular: {
    key: 'nomeTitular',
    label: 'Nome Completo do Titular',
    description: 'Nome completo da pessoa física ou razão social da pessoa jurídica titular do imóvel.',
    format: 'String (até 300 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Máximo de 300 caracteres.',
    example: 'JOÃO DA SILVA SAO PAULO',
  },
  percTitular: {
    key: 'percTitular',
    label: 'Percentual de Participação (%)',
    description: 'Porcentagem de direito ou participação do titular no imóvel.',
    format: 'Numérico - 1 inteiro + 4 decimais',
    mandatoryRule: 'Obrigatório se niTitular ou nomeTitular estiver preenchido.',
    rules: 'Limite de 1 dígito inteiro e 4 decimais (ex: 100.0000, 50.0000 ou 0.5000).',
    example: '100.0000',
  },
  dtAquisicaoTitular: {
    key: 'dtAquisicaoTitular',
    label: 'Data da Aquisição',
    description: 'Data de aquisição ou emissão do título de propriedade do titular.',
    format: 'Data (YYYY-MM-DD)',
    mandatoryRule: 'Obrigatório se niTitular ou nomeTitular estiver preenchido.',
    rules: 'Ano com 4 dígitos, mês e dia com 2 dígitos separados por hífen.',
    example: '2023-05-10',
  },
  tipoTitularidade: {
    key: 'tipoTitularidade',
    label: 'Tipo de Titularidade',
    description: 'Classificação do tipo de titularidade (ex.: Proprietário, Nu proprietário, Usufrutuário, Devedor Fiduciante, Arrendatário).',
    format: 'Inteiro (Tabela de Domínio SINTER - 1 a 17)',
    mandatoryRule: 'Obrigatório se niTitular ou nomeTitular estiver preenchido.',
    rules: 'Código do domínio SINTER (01 a 17). Ex: 1 = Proprietário, 2 = Nu proprietário, 8 = Usufrutuário, 17 = Arrendatário.',
    example: '1 (Proprietário)',
  },
  docTitularidade: {
    key: 'docTitularidade',
    label: 'Documento de Titularidade',
    description: 'Tipo de documento que comprova a titularidade (ex.: Escritura Pública, Contrato com força de Escritura, Instrumento Particular).',
    format: 'Inteiro (Tabela de Domínio SINTER - 1 a 5)',
    mandatoryRule: 'Obrigatório se niTitular ou nomeTitular estiver preenchido.',
    rules: 'Código do domínio SINTER (01 a 05). Ex: 1 = Escritura Pública, 3 = Instrumento Particular, 5 = Documento de Posse Emitido por Órgão Público.',
    example: '1 (Escritura Pública)',
  },
  nomeServentiaRI: {
    key: 'nomeServentiaRI',
    label: 'Nome da Serventia RI',
    description: 'Nome do cartório/serventia do Registro de Imóveis.',
    format: 'String (até 300 caracteres)',
    mandatoryRule: 'Opcional (pode ser omitido se cnsRI for informado).',
    rules: 'Até 300 caracteres.',
    example: '1º Cartório de Registro de Imóveis de Brasília',
  },
  cnsRI: {
    key: 'cnsRI',
    label: 'Código CNS do Registro de Imóveis',
    description: 'Código Nacional da Serventia (CNS) de Registro de Imóveis.',
    format: 'Inteiro (6 dígitos)',
    mandatoryRule: 'Opcional (se informado, nomeServentiaRI pode ser omitido).',
    rules: '6 dígitos numéricos do CNS.',
    example: '012345',
  },
  cnmRI: {
    key: 'cnmRI',
    label: 'Código Nacional da Matrícula (CNM)',
    description: 'Código nacional da matrícula no padrão CNJ Provimento 143 (CCCCCC.L.NNNNNNN-DD).',
    format: 'String (16 caracteres)',
    mandatoryRule: 'Opcional (se informado, demais campos de RI podem ser dispensados. Se não informado, para caracterizar o RI é necessário combinar os demais campos).',
    rules: 'CCCCCC (CNS - 6 dígitos), L=2 (Livro 2), NNNNNNN (nº ordem matrícula - 7 dígitos), DD (dígitos verificadores Módulo 97 Base 10 ISO 7064).',
    example: '012345.2.0001234-56',
  },
  numMatriculaRI: {
    key: 'numMatriculaRI',
    label: 'Número da Matrícula RI',
    description: 'Número da matrícula do imóvel no Registro de Imóveis.',
    format: 'String (até 15 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Até 15 caracteres.',
    example: '123456',
  },
  numUltimoAtoRI: {
    key: 'numUltimoAtoRI',
    label: 'Número do Último Ato',
    description: 'Número de identificação do último ato registrado na matrícula (ex: R-1, AV-2).',
    format: 'String (até 7 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Até 7 caracteres.',
    example: 'R-12345',
  },
  lvCartRI: {
    key: 'lvCartRI',
    label: 'Livro Cartorial RI',
    description: 'Identificação do livro cartorial do registro.',
    format: 'String (até 4 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Até 4 caracteres.',
    example: '2-A',
  },
  flCartRI: {
    key: 'flCartRI',
    label: 'Folha do Livro RI',
    description: 'Número ou código da folha do livro cartorial.',
    format: 'String (até 4 caracteres)',
    mandatoryRule: 'Opcional.',
    rules: 'Até 4 caracteres.',
    example: '150',
  },
  dtUltAtualizacao: {
    key: 'dtUltAtualizacao',
    label: 'Data da Última Atualização RI',
    description: 'Data da última atualização da informação do Registro de Imóveis.',
    format: 'Data (YYYY-MM-DD)',
    mandatoryRule: 'Opcional.',
    rules: 'Ano com 4 dígitos, mês e dia com 2 dígitos.',
    example: '2024-12-01',
  },
  nomeServentiaNotas: {
    key: 'nomeServentiaNotas',
    label: 'Nome da Serventia (Notas)',
    description: 'Nome do Cartório de Notas / Tabelionato onde foi lavrado o ato.',
    format: 'String (até 300 caracteres)',
    mandatoryRule: 'Opcional (se cnsNotas for informado ou para caracterizar Cartório de Notas junto com lvCartNotas e flCartNotas).',
    rules: 'Até 300 caracteres. Pode ser omitido se cnsNotas for informado.',
    example: '2º Tabelionato de Notas e Protestos',
  },
  cnsNotas: {
    key: 'cnsNotas',
    label: 'CNS Cartório de Notas',
    description: 'Código Nacional da Serventia do Cartório de Notas/Tabelionato atribuído pelo CNJ.',
    format: 'Inteiro (6 dígitos)',
    mandatoryRule: 'Opcional (preferencial em relação ao nomeServentiaNotas).',
    rules: 'Número inteiro positivo de exatamente 6 dígitos.',
    example: '098765',
  },
  lvCartNotas: {
    key: 'lvCartNotas',
    label: 'Livro do Cartório de Notas',
    description: 'Número ou identificação do livro do cartório de notas em que foi lavrada a escritura.',
    format: 'String (até 4 caracteres)',
    mandatoryRule: 'Opcional (necessário para caracterizar o Cartório de Notas junto a cnsNotas/nomeServentiaNotas e flCartNotas).',
    rules: 'Até 4 caracteres.',
    example: '120A',
  },
  flCartNotas: {
    key: 'flCartNotas',
    label: 'Folha do Cartório de Notas',
    description: 'Número da folha do livro do cartório de notas.',
    format: 'String (até 4 caracteres)',
    mandatoryRule: 'Opcional (necessário para caracterizar o Cartório de Notas junto a cnsNotas/nomeServentiaNotas e lvCartNotas).',
    rules: 'Até 4 caracteres.',
    example: '045',
  },
  baseCalculITBI: {
    key: 'baseCalculITBI',
    label: 'Base de Cálculo do ITBI (R$)',
    description: 'Valor sobre o qual é calculado o Imposto sobre Transmissão de Bens Imóveis (ITBI) da última transação.',
    format: 'Numérico - 18 inteiros + 2 decimais',
    mandatoryRule: 'Opcional. Se informado algum campo do ITBI, torna-se obrigatório.',
    rules: 'Número positivo com até 18 dígitos inteiros e 2 casas decimais.',
    example: '350000.00',
  },
  valorRefITBI: {
    key: 'valorRefITBI',
    label: 'Valor de Referência de ITBI (R$)',
    description: 'Valor de referência cadastral da prefeitura para apuração ou base de cálculo do ITBI.',
    format: 'Numérico - 18 inteiros + 2 decimais',
    mandatoryRule: 'Opcional. Se informado algum campo do ITBI, torna-se obrigatório.',
    rules: 'Número positivo com até 18 dígitos inteiros e 2 casas decimais.',
    example: '380000.00',
  },
  dtTransacaoITBI: {
    key: 'dtTransacaoITBI',
    label: 'Data da Transação (ITBI)',
    description: 'Data da ocorrência do fato gerador ou guia do ITBI da última transação.',
    format: 'Data (YYYY-MM-DD)',
    mandatoryRule: 'Opcional. Se informado algum campo do ITBI, torna-se obrigatório.',
    rules: 'Ano com 4 dígitos, mês e dia com 2 dígitos no padrão ISO YYYY-MM-DD.',
    example: '2024-05-15',
  },
  tpTransacaoITBI: {
    key: 'tpTransacaoITBI',
    label: 'Tipo da Transação (ITBI)',
    description: 'Código de identificação da natureza jurídica da transação imobiliária onerosa.',
    format: 'Inteiro (2 dígitos)',
    mandatoryRule: 'Opcional. Se informado algum campo do ITBI, torna-se obrigatório.',
    rules: 'Inteiro de 2 dígitos conforme tabela SINTER (01 a 37 - ex: 01 = Compra e Venda, 02 = Usufruto, 08 = Permuta, 37 = Promessa de Compra e Venda).',
    example: '01',
  },
  percTransacionadoITBI: {
    key: 'percTransacionadoITBI',
    label: 'Percentual Transacionado (ITBI)',
    description: 'Fração ideal ou percentual do imóvel envolvido na transação declarada.',
    format: 'Numérico - 1 inteiro + 6 decimais',
    mandatoryRule: 'Opcional. Se informado algum campo do ITBI, torna-se obrigatório.',
    rules: 'Limite de 1 inteiro e 6 casas decimais (ex: 1.000000 = 100%, 0.500000 = 50%).',
    example: '1.000000',
  },
  nomeTransmitenteITBI: {
    key: 'nomeTransmitenteITBI',
    label: 'Nome do Transmitente (ITBI)',
    description: 'Nome completo ou razão social de quem transmitiu o imóvel na última transação de ITBI.',
    format: 'String (até 300 caracteres)',
    mandatoryRule: 'Obrigatorio no bloco de Transmitentes de ITBI.',
    rules: 'Sem caracteres de controle. Máximo 300 caracteres.',
    example: 'MARIA DAS DORES SANTOS',
  },
  niTransmitenteITBI: {
    key: 'niTransmitenteITBI',
    label: 'NI Transmitente (CPF/CNPJ)',
    description: 'Número do CPF (11 dígitos) ou CNPJ (14 dígitos) do transmitente no ITBI.',
    format: 'String numérica (11 ou 14 dígitos)',
    mandatoryRule: 'Obrigatório para identificação do transmitente.',
    rules: 'Apenas números (11 dígitos para CPF, 14 para CNPJ).',
    example: '12345678901',
  },
  nomeAdquirenteITBI: {
    key: 'nomeAdquirenteITBI',
    label: 'Nome do Adquirente (ITBI)',
    description: 'Nome completo ou razão social do adquirente do imóvel na última transação de ITBI.',
    format: 'String (até 300 caracteres)',
    mandatoryRule: 'Obrigatório no bloco de Adquirentes de ITBI.',
    rules: 'Sem caracteres de controle. Máximo 300 caracteres.',
    example: 'JOÃO PEDRO OLIVEIRA',
  },
  niAdquirenteITBI: {
    key: 'niAdquirenteITBI',
    label: 'NI Adquirente (CPF/CNPJ)',
    description: 'Número do CPF (11 dígitos) ou CNPJ (14 dígitos) do adquirente no ITBI.',
    format: 'String numérica (11 ou 14 dígitos)',
    mandatoryRule: 'Obrigatório para identificação do adquirente.',
    rules: 'Apenas números (11 dígitos para CPF, 14 para CNPJ).',
    example: '98765432100',
  },
  percTransacAdquirenteITBI: {
    key: 'percTransacAdquirenteITBI',
    label: 'Percentual Transacionado do Adquirente (%)',
    description: 'Percentual do imóvel adquirido por este adquirente na transação.',
    format: 'Numérico - 1 inteiro + 6 decimais',
    mandatoryRule: 'Obrigatório para cada adquirente do ITBI.',
    rules: 'Limite de 1 inteiro e 6 casas decimais (ex: 1.000000 = 100%, 0.500000 = 50%).',
    example: '1.000000',
  },
};

/**
 * Safely retrieves help info for a field key with a safe fallback
 */
export function getFieldHelp(key: string): FieldHelpInfo {
  if (SINTER_FIELDS_HELP[key]) {
    return SINTER_FIELDS_HELP[key];
  }
  return {
    key,
    label: key,
    description: `Campo cadastral: ${key}`,
    format: 'Padrão SINTER',
    mandatoryRule: 'Conforme regras gerais.',
    rules: 'Sem caracteres invisíveis.',
    example: '',
  };
}

/**
 * Strips invisible/control characters (ASCII 0-31 except tab/LF, and zero-width spaces)
 */
export function sanitizeTextInput(input: string): string {
  if (!input) return '';
  return input
    // Remove zero-width characters (ZWSP, ZWNJ, ZWJ, BOM)
    .replace(/[\u200B-\u200D\uFEFF\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g, '')
    // Replace non-breaking spaces with standard space
    .replace(/\u00A0/g, ' ')
    // Normalize unicode
    .normalize('NFC');
}
