import { NDJsonRecord, OptionItem } from './types';

// Default initial state for a new record form (option fields start empty/0 by default)
export const DEFAULT_RECORD_DADOS: NDJsonRecord['dadosGerais'] = {
  inscricaoImobiliaria: '',
  temBairro: true,
  tipoImovel: 0,
  tpArquitetonico: 0,
  destinacaoImovel: 0,
  areaTerreno: 0,
  areaConstruida: 0,
  anoConstrutivo: 0,
  bice: 0,
};

export const DEFAULT_RECORD_ENDERECO: NDJsonRecord['endereco'] = {
  tipoLogradouro: 0,
  nomeLogradouro: '',
  bairro: '',
  numeroImovel: '',
  complNroImovel: '',
  complEndereco: '',
  cep: '',
};

export const DEFAULT_OPERACAO = 'I';

// Complete list of Tipo de Logradouro (311 items)
export const TIPO_LOGRADOURO_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Acampamento' },
  { value: 2, label: '02 - Acesso' },
  { value: 3, label: '03 - Açude' },
  { value: 4, label: '04 - Adro' },
  { value: 5, label: '05 - Aeroporto' },
  { value: 6, label: '06 - Afluente' },
  { value: 7, label: '07 - Aglomerado' },
  { value: 8, label: '08 - Agrovila' },
  { value: 9, label: '09 - Alagado' },
  { value: 10, label: '10 - Alameda' },
  { value: 11, label: '11 - Aldeia' },
  { value: 12, label: '12 - Aleia' },
  { value: 13, label: '13 - Alto' },
  { value: 14, label: '14 - Anel' },
  { value: 15, label: '15 - Antiga' },
  { value: 16, label: '16 - Antigo' },
  { value: 17, label: '17 - Area' },
  { value: 18, label: '18 - Areal' },
  { value: 19, label: '19 - Arraial' },
  { value: 20, label: '20 - Arroio' },
  { value: 21, label: '21 - Artéria' },
  { value: 22, label: '22 - Assentamento' },
  { value: 23, label: '23 - Atalho' },
  { value: 24, label: '24 - Aterro' },
  { value: 25, label: '25 - Autódromo' },
  { value: 26, label: '26 - Avenida' },
  { value: 27, label: '27 - Baia' },
  { value: 28, label: '28 - Bairro' },
  { value: 29, label: '29 - Baixa' },
  { value: 30, label: '30 - Baixada' },
  { value: 31, label: '31 - Baixadão' },
  { value: 32, label: '32 - Baixão' },
  { value: 33, label: '33 - Baixo' },
  { value: 34, label: '34 - Balão' },
  { value: 35, label: '35 - Balneário' },
  { value: 36, label: '36 - Barra' },
  { value: 37, label: '37 - Barragem' },
  { value: 38, label: '38 - Barranca' },
  { value: 39, label: '39 - Barranco' },
  { value: 40, label: '40 - Barreiro' },
  { value: 41, label: '41 - Barro' },
  { value: 42, label: '42 - Beco' },
  { value: 43, label: '43 - Beira' },
  { value: 44, label: '44 - Beirada' },
  { value: 45, label: '45 - Belvedere' },
  { value: 46, label: '46 - Bloco' },
  { value: 47, label: '47 - Bocaina' },
  { value: 48, label: '48 - Boqueirão' },
  { value: 49, label: '49 - Bosque' },
  { value: 50, label: '50 - Boulevard' },
  { value: 51, label: '51 - Brejo' },
  { value: 52, label: '52 - Buraco' },
  { value: 53, label: '53 - Cabeceira' },
  { value: 54, label: '54 - Cachoeira' },
  { value: 55, label: '55 - Cachoeirinha' },
  { value: 56, label: '56 - Cais' },
  { value: 57, label: '57 - Calcada' },
  { value: 58, label: '58 - Calçadão' },
  { value: 59, label: '59 - Caminho' },
  { value: 60, label: '60 - Campo' },
  { value: 61, label: '61 - Canal' },
  { value: 62, label: '62 - Canteiro' },
  { value: 63, label: '63 - Capão' },
  { value: 64, label: '64 - Capoeira' },
  { value: 65, label: '65 - Cartódromo' },
  { value: 66, label: '66 - Central' },
  { value: 67, label: '67 - Centro' },
  { value: 68, label: '68 - Cerca' },
  { value: 69, label: '69 - Cerrado' },
  { value: 70, label: '70 - Cerro' },
  { value: 71, label: '71 - Chácara' },
  { value: 72, label: '72 - Chapada' },
  { value: 73, label: '73 - Chapadão' },
  { value: 74, label: '74 - Charco' },
  { value: 75, label: '75 - Cidade' },
  { value: 76, label: '76 - Circular' },
  { value: 77, label: '77 - Cohab' },
  { value: 78, label: '78 - Colina' },
  { value: 79, label: '79 - Colônia' },
  { value: 80, label: '80 - Comunidade' },
  { value: 81, label: '81 - Condomínio' },
  { value: 82, label: '82 - Conjunto' },
  { value: 83, label: '83 - Continuação' },
  { value: 84, label: '84 - Contorno' },
  { value: 85, label: '85 - Corredor' },
  { value: 86, label: '86 - Córrego' },
  { value: 87, label: '87 - Costa' },
  { value: 88, label: '88 - Coxilha' },
  { value: 89, label: '89 - Cruzamento' },
  { value: 90, label: '90 - Descida' },
  { value: 91, label: '91 - Desvio' },
  { value: 92, label: '92 - Dique' },
  { value: 93, label: '93 - Distrito' },
  { value: 94, label: '94 - Divisa' },
  { value: 95, label: '95 - Divisão' },
  { value: 96, label: '96 - Divisor' },
  { value: 97, label: '97 - Edifício' },
  { value: 98, label: '98 - Eixo' },
  { value: 99, label: '99 - Elevado' },
  { value: 100, label: '100 - Encosta' },
  { value: 101, label: '101 - Engenho' },
  { value: 102, label: '102 - Enseada' },
  { value: 103, label: '103 - Entrada' },
  { value: 104, label: '104 - Entreposto' },
  { value: 105, label: '105 - Entroncamento' },
  { value: 106, label: '106 - Escada' },
  { value: 107, label: '107 - Escadão' },
  { value: 108, label: '108 - Escadaria' },
  { value: 109, label: '109 - Escadinha' },
  { value: 110, label: '110 - Espigão' },
  { value: 111, label: '111 - Esplanada' },
  { value: 112, label: '112 - Esquina' },
  { value: 113, label: '113 - Estação' },
  { value: 114, label: '114 - Estacionamento' },
  { value: 115, label: '115 - Estádio' },
  { value: 116, label: '116 - Estância' },
  { value: 117, label: '117 - Estrada' },
  { value: 118, label: '118 - Extensão' },
  { value: 119, label: '119 - Faixa' },
  { value: 120, label: '120 - Favela' },
  { value: 121, label: '121 - Fazenda' },
  { value: 122, label: '122 - Feira' },
  { value: 123, label: '123 - Ferrovia' },
  { value: 124, label: '124 - Final' },
  { value: 125, label: '125 - Floresta' },
  { value: 126, label: '126 - Folha' },
  { value: 127, label: '127 - Fonte' },
  { value: 128, label: '128 - Fortaleza' },
  { value: 129, label: '129 - Freguesia' },
  { value: 130, label: '130 - Fundos' },
  { value: 131, label: '131 - Furo' },
  { value: 132, label: '132 - Galeria' },
  { value: 133, label: '133 - Gameleira' },
  { value: 134, label: '134 - Garimpo' },
  { value: 135, label: '135 - Gleba' },
  { value: 136, label: '136 - Granja' },
  { value: 137, label: '137 - Grota' },
  { value: 138, label: '138 - Habitacional' },
  { value: 139, label: '139 - Haras' },
  { value: 140, label: '140 - Hipódromo' },
  { value: 141, label: '141 - Horto' },
  { value: 142, label: '142 - Igarapé' },
  { value: 143, label: '143 - Ilha' },
  { value: 144, label: '144 - Inaplicável' },
  { value: 145, label: '145 - Invasão' },
  { value: 146, label: '146 - Jardim' },
  { value: 147, label: '147 - Jardinete' },
  { value: 148, label: '148 - Ladeira' },
  { value: 149, label: '149 - Lado' },
  { value: 150, label: '150 - Lago' },
  { value: 151, label: '151 - Lagoa' },
  { value: 152, label: '152 - Lagoinha' },
  { value: 153, label: '153 - Largo' },
  { value: 154, label: '154 - Lateral' },
  { value: 155, label: '155 - Leito' },
  { value: 156, label: '156 - Ligação' },
  { value: 157, label: '157 - Limeira' },
  { value: 158, label: '158 - Limite' },
  { value: 159, label: '159 - Limites' },
  { value: 160, label: '160 - Linha' },
  { value: 161, label: '161 - Lote' },
  { value: 162, label: '162 - Loteamento' },
  { value: 163, label: '163 - Lugarejo' },
  { value: 164, label: '164 - Maloca' },
  { value: 165, label: '165 - Manancial' },
  { value: 166, label: '166 - Mangue' },
  { value: 167, label: '167 - Margem' },
  { value: 168, label: '168 - Margens' },
  { value: 169, label: '169 - Marginal' },
  { value: 170, label: '170 - Marina' },
  { value: 171, label: '171 - Mata' },
  { value: 172, label: '172 - Mato' },
  { value: 173, label: '173 - Módulo' },
  { value: 174, label: '174 - Monte' },
  { value: 175, label: '175 - Morro' },
  { value: 176, label: '176 - Muro' },
  { value: 177, label: '177 - Não Especificado' },
  { value: 178, label: '178 - Núcleo' },
  { value: 179, label: '179 - Oca' },
  { value: 180, label: '180 - Oleoduto' },
  { value: 181, label: '181 - Olho' },
  { value: 182, label: '182 - Olhos' },
  { value: 183, label: '183 - Orla' },
  { value: 184, label: '184 - Outros' },
  { value: 185, label: '185 - Paco' },
  { value: 186, label: '186 - Palafita' },
  { value: 187, label: '187 - Pântano' },
  { value: 188, label: '188 - Parada' },
  { value: 189, label: '189 - Paradouro' },
  { value: 190, label: '190 - Paralela' },
  { value: 191, label: '191 - Parque' },
  { value: 192, label: '192 - Particular' },
  { value: 193, label: '193 - Passagem' },
  { value: 194, label: '194 - Passarela' },
  { value: 195, label: '195 - Passeio' },
  { value: 196, label: '196 - Passo' },
  { value: 197, label: '197 - Pasto' },
  { value: 198, label: '198 - Pátio' },
  { value: 199, label: '199 - Pavilhão' },
  { value: 200, label: '200 - Pedra' },
  { value: 201, label: '201 - Pedras' },
  { value: 202, label: '202 - Pedreira' },
  { value: 203, label: '203 - Penhasco' },
  { value: 204, label: '204 - Perimetral' },
  { value: 205, label: '205 - Perímetro' },
  { value: 206, label: '206 - Perto' },
  { value: 207, label: '207 - Planalto' },
  { value: 208, label: '208 - Plataforma' },
  { value: 209, label: '209 - Ponta' },
  { value: 210, label: '210 - Ponte' },
  { value: 211, label: '211 - Ponto' },
  { value: 212, label: '212 - Porto' },
  { value: 213, label: '213 - Posto' },
  { value: 214, label: '214 - Povoado' },
  { value: 215, label: '215 - Praça' },
  { value: 216, label: '216 - Praia' },
  { value: 217, label: '217 - Projeção' },
  { value: 218, label: '218 - Projetada' },
  { value: 219, label: '219 - Projeto' },
  { value: 220, label: '220 - Prolongamento' },
  { value: 221, label: '221 - Propriedade' },
  { value: 222, label: '222 - Próximo' },
  { value: 223, label: '223 - Quadra' },
  { value: 224, label: '224 - Quarteirão' },
  { value: 225, label: '225 - Quilombo' },
  { value: 226, label: '226 - Quilômetro' },
  { value: 227, label: '227 - Quinta' },
  { value: 228, label: '228 - Quintas' },
  { value: 229, label: '229 - Rachão' },
  { value: 230, label: '230 - Ramal' },
  { value: 231, label: '231 - Rampa' },
  { value: 232, label: '232 - Rancho' },
  { value: 233, label: '233 - Recanto' },
  { value: 234, label: '234 - Região' },
  { value: 235, label: '235 - Represa' },
  { value: 236, label: '236 - Residencial' },
  { value: 237, label: '237 - Reta' },
  { value: 238, label: '238 - Retiro' },
  { value: 239, label: '239 - Retorno' },
  { value: 240, label: '240 - Riacho' },
  { value: 241, label: '241 - Ribanceira' },
  { value: 242, label: '242 - Ribeirão' },
  { value: 243, label: '243 - Rincão' },
  { value: 244, label: '244 - Rio' },
  { value: 245, label: '245 - Rocha' },
  { value: 246, label: '246 - Rochedo' },
  { value: 247, label: '247 - Rodovia' },
  { value: 248, label: '248 - Rotatória' },
  { value: 249, label: '249 - Rotula' },
  { value: 250, label: '250 - Rua' },
  { value: 251, label: '251 - Ruela' },
  { value: 252, label: '252 - Saco' },
  { value: 253, label: '253 - Saída' },
  { value: 254, label: '254 - Sanga' },
  { value: 255, label: '255 - Sede' },
  { value: 256, label: '256 - Sem' },
  { value: 257, label: '257 - Seringal' },
  { value: 258, label: '258 - Serra' },
  { value: 259, label: '259 - Sertão' },
  { value: 260, label: '260 - Servidão' },
  { value: 261, label: '261 - Seta' },
  { value: 262, label: '262 - Setor' },
  { value: 263, label: '263 - Sitio' },
  { value: 264, label: '264 - Sopé' },
  { value: 265, label: '265 - Subida' },
  { value: 266, label: '266 - Superquadra' },
  { value: 267, label: '267 - Tapera' },
  { value: 268, label: '268 - Terminal' },
  { value: 269, label: '269 - Terra' },
  { value: 270, label: '270 - Terreno' },
  { value: 271, label: '271 - Terrenos' },
  { value: 272, label: '272 - Transversal' },
  { value: 273, label: '273 - Travessa' },
  { value: 274, label: '274 - Travessão' },
  { value: 275, label: '275 - Travessia' },
  { value: 276, label: '276 - Trecho' },
  { value: 277, label: '277 - Trevo' },
  { value: 278, label: '278 - Trilha' },
  { value: 279, label: '279 - Trilho' },
  { value: 280, label: '280 - Trilhos' },
  { value: 281, label: '281 - Trincheira' },
  { value: 282, label: '282 - Túnel' },
  { value: 283, label: '283 - Unidade' },
  { value: 284, label: '284 - Usina' },
  { value: 285, label: '285 - Vala' },
  { value: 286, label: '286 - Valão' },
  { value: 287, label: '287 - Vale' },
  { value: 288, label: '288 - Vargem' },
  { value: 289, label: '289 - Variante' },
  { value: 290, label: '290 - Várzea' },
  { value: 291, label: '291 - Velódromo' },
  { value: 292, label: '292 - Vereda' },
  { value: 293, label: '293 - Vertente' },
  { value: 294, label: '294 - Via' },
  { value: 295, label: '295 - Viaduto' },
  { value: 296, label: '296 - Vicinal' },
  { value: 297, label: '297 - Viela' },
  { value: 298, label: '298 - Vila' },
  { value: 299, label: '299 - Vilarejo' },
  { value: 300, label: '300 - Volta' },
  { value: 301, label: '301 - Zona' },
  { value: 302, label: '302 - 1a Travessa da Avenida' },
  { value: 303, label: '303 - 1a Travessa da Rua' },
  { value: 304, label: '304 - 2a Travessa da Avenida' },
  { value: 305, label: '305 - 2a Travessa da Rua' },
  { value: 306, label: '306 - 3a Travessa da Avenida' },
  { value: 307, label: '307 - 3a Travessa da Rua' },
  { value: 308, label: '308 - 4a Travessa da Avenida' },
  { value: 309, label: '309 - 4a Travessa da Rua' },
  { value: 310, label: '310 - 5a Travessa da Avenida' },
  { value: 311, label: '311 - 5a Travessa da Rua' },
];

export const TIPO_IMOVEL_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Territorial (sem edificação)' },
  { value: 2, label: '02 - Predial (com edificação)' },
  { value: 3, label: '03 - Bem imóvel de características especiais' },
];

export const TP_ARQUITETONICO_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Casa' },
  { value: 2, label: '02 - Apartamento' },
  { value: 3, label: '03 - Vaga de garagem' },
  { value: 4, label: '04 - Lage' },
  { value: 5, label: '05 - Sala' },
  { value: 6, label: '06 - Conjunto de salas' },
  { value: 7, label: '07 - Loja' },
  { value: 8, label: '08 - Sobreloja' },
  { value: 9, label: '09 - Estacionamento' },
  { value: 10, label: '10 - Barraco' },
  { value: 11, label: '11 - Galpão' },
];

export const DESTINACAO_IMOVEL_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Residencial' },
  { value: 2, label: '02 - Comercial' },
  { value: 3, label: '03 - Prestação de serviço' },
  { value: 4, label: '04 - Industrial' },
  { value: 5, label: '05 - Educacional' },
  { value: 6, label: '06 - Lazer' },
  { value: 7, label: '07 - Desportos' },
  { value: 8, label: '08 - Religioso' },
  { value: 9, label: '09 - Institucional' },
  { value: 10, label: '10 - Transporte' },
  { value: 11, label: '11 - Comunicação' },
  { value: 12, label: '12 - Saúde' },
  { value: 13, label: '13 - Hotelaria' },
  { value: 14, label: '14 - Uso misto' },
  { value: 15, label: '15 - Urbano com destinação rural' },
  { value: 16, label: '16 - Bem de uso comum do povo' },
  { value: 17, label: '17 - Saneamento' },
  { value: 99, label: '99 - Não Residencial' },
];

export const PADRAO_CONSTRUTIVO_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Popular' },
  { value: 2, label: '02 - Baixo' },
  { value: 3, label: '03 - Normal' },
  { value: 4, label: '04 - Alto' },
  { value: 5, label: '05 - Luxo' },
];

export const BICE_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Usinas nucleares, hidrelétricas e termoelétricas' },
  { value: 2, label: '02 - Parques eólicos e plantas solares' },
  { value: 3, label: '03 - Plataformas, sondas de prospecção e plantas de refino de petróleo e gás' },
  { value: 4, label: '04 - Portos, eclusas, aeroportos, terminais rodoviários, ferroviários e hidroviários' },
  { value: 5, label: '05 - Aquedutos, gasodutos e minerodutos' },
  { value: 6, label: '06 - Aquíferos e jazidas minerais' },
  { value: 7, label: '07 - Rodovias, estradas, vias vicinais, túneis, pontes e viadutos' },
  { value: 8, label: '08 - Praças e logradouros' },
  { value: 9, label: '09 - Museus, prédios e monumentos históricos e sítios arqueológicos' },
  { value: 10, label: '10 - Terras indígenas e terras devolutas' },
  { value: 11, label: '11 - Lagos, lagoas, rios, quedas d´água, reservatórios de barragens, açudes, cursos d’água navegáveis, mananciais e espelho d’água' },
  { value: 12, label: '12 - Parques, florestas, áreas ambientais e unidades de conservação' },
];

export const OPERACAO_OPTIONS: OptionItem[] = [
  { value: 'I', label: 'I - Inclusão de UI' },
  { value: 'A', label: 'A - Alteração de UI' },
  { value: 'D', label: 'D - Desativação de UI' },
];

export const TIPO_DESATIVACAO_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Extinção' },
  { value: 2, label: '02 - Nulidade' },
];

export const MOTIVO_DESATIVACAO_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Desmembramento (Extinção)' },
  { value: 2, label: '02 - Remembramento (Extinção)' },
  { value: 3, label: '03 - Incorporação (Extinção)' },
  { value: 4, label: '04 - Loteamento (Extinção)' },
  { value: 5, label: '05 - Constituição de condomínio (Extinção)' },
  { value: 6, label: '06 - Decisão administrativa (Extinção e Nulidade)' },
  { value: 7, label: '07 - Decisão judicial (Extinção e Nulidade)' },
  { value: 8, label: '08 - Destinação rural (Nulidade)' },
  { value: 9, label: '09 - Duplicidade (Nulidade)' },
  { value: 10, label: '10 - Inscrição indevida (Nulidade)' },
];

export const SINTER_FAILURE_CODES: Record<string, string> = {
  '0001': 'Campo obrigatório não preenchido',
  '0002': 'Campo com formatação inválida',
  '0003': 'Campo com tamanho inválido',
  '0004': 'Campo com código não encontrado em tabela de domínio',
  '0005': 'Campo com valor inválido',
  '0006': 'Unidade Imobiliária já cadastrada no SINTER',
  '0007': 'Unidade Imobiliária não encontrada no SINTER',
  '0008': 'CIB incompatível com Inscrição Imobiliária',
  '0009': 'Situação da Unidade Imobiliária não permite alteração',
  '0010': 'Campo com preenchimento indevido',
  '0011': "Para este 'tipoImovel', 'tpArquitetonico' e 'areaConstruida' devem ser null",
  '0012': "Para este 'tipoImovel', 'tpArquitetonico' e 'areaConstruida' são obrigatórios e devem ser válidos",
  '0013': "Para este 'tipoImovel', 'bice' é obrigatório e deve ser válido",
  '0014': "Quando 'DadosGeraisImovel.temBairro' for true, 'EnderecoImovel.bairro' é obrigatório",
  '0015': "Para este 'tipoImovel', 'destinacaoImovel' é obrigatório e deve ser válido",
  '0016': 'Json com campo inválido ou estrutura inválida',
  '0101': 'Campos com preenchimento incompatível',
  '0102': 'Campo com formato inválido',
  '0103': 'Campo com tamanho inválido',
  '0104': 'Campo com código não encontrado em tabela de domínio',
  '0105': 'Campo com valor inválido',
  '0106': 'CPF/CNPJ com DV inválido',
  '0107': 'Data com formato inválido',
  '0108': 'Grupo com preenchimento incompleto ou inválido',
  '0099': 'Erro técnico no processamento da UI',
};

export const TIPO_TITULARIDADE_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Proprietário' },
  { value: 2, label: '02 - Nu proprietário' },
  { value: 3, label: '03 - Senhorio Direto' },
  { value: 4, label: '04 - Credor Fiduciário' },
  { value: 5, label: '05 - Possuidor a justo título' },
  { value: 6, label: '06 - Possuidor por simples ocupação' },
  { value: 7, label: '07 - Enfiteuta' },
  { value: 8, label: '08 - Usufrutuário' },
  { value: 9, label: '09 - Devedor Fiduciante' },
  { value: 10, label: '10 - Usuário' },
  { value: 11, label: '11 - Superficiário' },
  { value: 12, label: '12 - Concessionário do Direito Real de Uso' },
  { value: 13, label: '13 - Habitador' },
  { value: 14, label: '14 - Promitente comprador (com registro sem cláusula de arrependimento)' },
  { value: 15, label: '15 - Concessionário (contrato de concessão de uso)' },
  { value: 16, label: '16 - Promitente comprador (demais)' },
  { value: 17, label: '17 - Arrendatário' },
];

export const DOC_TITULARIDADE_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - Escritura Pública' },
  { value: 2, label: '02 - Contrato com força de Escritura' },
  { value: 3, label: '03 - Instrumento Particular' },
  { value: 4, label: '04 - Sentença Judicial' },
  { value: 5, label: '05 - Documento de Posse Emitido por Órgão Público' },
];

export const TP_TRANSACAO_ITBI_OPTIONS: OptionItem[] = [
  { value: 1, label: '01 - COMPRA E VENDA' },
  { value: 2, label: '02 - USUFRUTO' },
  { value: 3, label: '03 - NUA PROPRIEDADE' },
  { value: 4, label: '04 - CESSÃO DE DIREITOS' },
  { value: 5, label: '05 - DAÇÃO EM PAGAMENTO' },
  { value: 6, label: '06 - EXTINÇÃO DE CONDOMÍNIO' },
  { value: 7, label: '07 - INTEGRALIZAÇÃO DE CAPITAL' },
  { value: 8, label: '08 - PERMUTA' },
  { value: 9, label: '09 - INTERVENIÊNCIA' },
  { value: 10, label: '10 - ADJUDICAÇÃO' },
  { value: 11, label: '11 - COMPRA E VENDA COM INTERVENIÊNCIA' },
  { value: 12, label: '12 - CISÃO' },
  { value: 13, label: '13 - ARREMATAÇÃO JUDICIAL' },
  { value: 14, label: '14 - DISTRATO' },
  { value: 15, label: '15 - RENÚNCIA DE USUFRUTO' },
  { value: 16, label: '16 - EXTINÇÃO DE PESSOA JURÍDICA' },
  { value: 17, label: '17 - TORNA SOBRE EXTINÇÃO DE CONDOMÍNIO' },
  { value: 18, label: '18 - DESINCORPORAÇÃO DE CAPITAL' },
  { value: 19, label: '19 - INCORPORAÇÃO DE SOCIEDADE' },
  { value: 20, label: '20 - DESAPROPRIAÇÃO' },
  { value: 21, label: '21 - CONSOLIDAÇÃO DA PROPRIEDADE' },
  { value: 22, label: '22 - DISTRIBUIÇÃO DE LUCROS E RESULTADOS' },
  { value: 23, label: '23 - PARTILHA DE BENS EM AÇÃO JUDICIAL (MEAÇÃO)' },
  { value: 24, label: '24 - REDUÇÃO DE CAPITAL' },
  { value: 25, label: '25 - FUSÃO' },
  { value: 26, label: '26 - TRANSAÇÃO JUDICIAL' },
  { value: 27, label: '27 - USUCAPIÃO' },
  { value: 28, label: '28 - RESERVA DE ÁGIO' },
  { value: 29, label: '29 - RESERVA DE CAPITAL' },
  { value: 30, label: '30 - TRANSLAÇÃO DE DOMÍNIO' },
  { value: 31, label: '31 - DIREITO REAL DE AQUISIÇÃO' },
  { value: 32, label: '32 - CESSÃO DE DIREITOS HEREDITÁRIOS' },
  { value: 33, label: '33 - ALIENAÇÃO' },
  { value: 34, label: '34 - INSTITUIÇÃO DE DIREITO REAL DE GARANTIA' },
  { value: 35, label: '35 - INSTITUIÇÃO DO DIREITO DE SUPERFÍCIE' },
  { value: 36, label: '36 - ARREMATAÇÃO EXTRAJUDICIAL' },
  { value: 37, label: '37 - PROMESSA DE COMPRA E VENDA' },
];

// Sample initial data matching the exact 3 records requested in the user prompt
export const SAMPLE_RECORDS: NDJsonRecord[] = [
  {
    id: 'sample-1',
    dadosGerais: {
      inscricaoImobiliaria: '11',
      temBairro: true,
      tipoImovel: 2,
      tpArquitetonico: 2,
      destinacaoImovel: 1,
      areaTerreno: 165,
      areaConstruida: 145.26,
      anoConstrutivo: 1900,
    },
    endereco: {
      tipoLogradouro: 26,
      nomeLogradouro: '2 De Julho',
      bairro: 'São Sebastião',
      numeroImovel: '23',
      complNroImovel: 'PRIMEIRO ANDAR',
      complEndereco: 'EDIFÍCIO SALOMÃO',
      cep: '45653758',
    },
    operacao: 'I',
  },
  {
    id: 'sample-2',
    dadosGerais: {
      inscricaoImobiliaria: '66',
      temBairro: true,
      tipoImovel: 2,
      tpArquitetonico: 2,
      destinacaoImovel: 1,
      areaTerreno: 165,
      areaConstruida: 120.6,
      anoConstrutivo: 1900,
    },
    endereco: {
      tipoLogradouro: 26,
      nomeLogradouro: '2 De Julho',
      bairro: 'São Sebastião',
      numeroImovel: '23',
      complNroImovel: 'SEGUNDO ANDAR',
      complEndereco: 'EDIFÍCIO SALOMÃO',
      cep: '45653758',
    },
    operacao: 'I',
  },
  {
    id: 'sample-3',
    dadosGerais: {
      inscricaoImobiliaria: '68',
      temBairro: true,
      tipoImovel: 2,
      tpArquitetonico: 2,
      destinacaoImovel: 1,
      areaTerreno: 165,
      areaConstruida: 180.6,
      anoConstrutivo: 1900,
    },
    endereco: {
      tipoLogradouro: 26,
      nomeLogradouro: '2 De Julho',
      bairro: 'São Sebastião',
      numeroImovel: '23',
      complNroImovel: 'TERRÉO',
      complEndereco: 'EDIFÍCIO SALOMÃO',
      cep: '45653758',
    },
    operacao: 'I',
  },
  {
    id: 'sample-4',
    dadosGerais: {
      inscricaoImobiliaria: '1234567890123456789012345',
      temBairro: true,
      tipoImovel: 3,
      tpArquitetonico: 12,
      destinacaoImovel: 2,
      idParcela: 'PARC-12345',
      areaTerreno: 350.75,
      areaConstruida: 120.5,
      anoConstrutivo: 2005,
      valorVenal: 450000,
      dtUltimoValorVenal: '2024-12-01',
      padraoConstrutivo: 3,
      qtdGaragem: 2,
      temPiscina: false,
      valorRefMercado: 520000,
      dataUltValorMercado: '2024-12-15',
    },
    areaConstruidaCompl: {
      areaPrivativa: 100.25,
      areaComum: 20.25,
      fraIdeal: 0.5,
    },
    endereco: {
      tipoLogradouro: 100,
      nomeLogradouro: 'Avenida Brasil',
      bairro: 'Centro',
      cep: '70040900',
      numeroImovel: '1234',
      complNroImovel: 'BL A',
      complEndereco: 'APT 201',
    },
    titulares: [
      {
        niTitular: '12345678901',
        nomeTitular: 'JOAO DA SILVA',
        percTitular: 1,
        percTitularidade: 1,
        dtAquisicaoTitular: '2023-05-20',
        tipoTitularidade: 1,
        docTitularidade: 1,
      },
    ],
    servicoRegistroImovel: {
      nomeServentiaRI: '1º REGISTRO DE IMOVEIS DA CAPITAL',
      cnsRI: 123456,
      numMatriculaRI: '123456',
      numUltimoAtoRI: 'AV-10',
      lvCartRI: '0002',
      flCartRI: '0100',
      dtUltAtualizacao: '2024-12-01',
    },
    cartorioNotas: {
      nomeServentiaNotas: '1º TABELIONATO DE NOTAS',
      cnsNotas: 123456,
      lvCartNotas: '0100',
      flCartNotas: '0050',
    },
    operacao: 'I',
  },
  {
    id: 'sample-5',
    dadosGerais: {
      inscricaoImobiliaria: '2234567890123456789012388',
      temBairro: true,
      tipoImovel: 3,
      tpArquitetonico: 11,
      destinacaoImovel: 2,
      idParcela: 'PARC-12345',
      areaTerreno: 350.75,
      areaConstruida: 120.5,
      bice: 1,
      anoConstrutivo: 2005,
      valorVenal: 450000,
      dtUltimoValorVenal: '2024-12-01',
      padraoConstrutivo: 3,
      qtdGaragem: 2,
      temPiscina: false,
      valorRefMercado: 520000,
      dataUltValorMercado: '2024-12-15',
    },
    areaConstruidaCompl: {
      areaPrivativa: 100.25,
      areaComum: 20.25,
      fraIdeal: 0.5,
    },
    endereco: {
      tipoLogradouro: 100,
      nomeLogradouro: 'Avenida Brasil',
      bairro: 'Centro',
      cep: '70040900',
      numeroImovel: '1234',
      complEndereco: 'APT 201',
    },
    titulares: [
      {
        niTitular: '12345678901',
        nomeTitular: 'JOAO DA SILVA',
        percTitular: 1,
        percTitularidade: 1,
        dtAquisicaoTitular: '2023-05-20',
        tipoTitularidade: 1,
        docTitularidade: 1,
      },
    ],
    operacao: 'I',
  },
];
